# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='compensation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
